### ISSUE TITLE
Incorrect plugin link in README?

### ISSUE THREAD

**Issue by mpetersheim** [BroJenuel-Visual-Studio/vue-volar-extension-pack#2]
Ahh, your readme (and the extension's Overview section in Visual Studio Marketplace) says this includes the official ESLint plugin but the link behind that text still points to the deprecated TSLint plugin; I'm assuming that's an oversight, but it would be nice to have it corrected.

**Comment by JenuelDev** [comment]
Thanks for pointing that out :)
